### ISSUE TITLE
workbench error whe .csv downloaded and Excel opens

### ISSUE THREAD

**Issue by volkcj** [NorthArrowResearch/champ-workbench#51]
After downloading the .csv of QA-Topo Tier 2 metrics from the Metric Review window of the workbench, I selected the option to 'open the .csv file'.

This error then occurs, but Excel goes on to open the .csv file.

Message: An error occurred in sending the command to the application
Type: Exception
Severity: Error
ExceptionSource: System
ErrorInMethod: StartWithShellExecuteEx
StackTrace:    at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at CHaMPWorkbench.Data.ucMetricGrid.exportMetricDataToCSVToolStripMenuItem_Click(Object sender, EventArgs e)
ProductVersion: 7.0.22.0
OSVersion: Microsoft Windows NT 6.2.9200.0

**Comment by philipbaileynar** [comment]
I can't reproduce this. Unsure how to proceed. Where did you choose to save the file? Was it somewhere obscure?
